swagger: '2.0'
info:
  title: Hello API
  version: "0.1"
basePath: "/api/v1"
paths:
  /hello/{name}:
    get:
      operationId: api.hello
      summary: Returns a greeting.
      parameters:
        - name: "name"
          in: "path"
          description: "Your name"
          required: true
          type: "string"
      responses:
        200:
          description: Successful response.
          schema:
            type: object
            properties:
              message:
                type: string
                description: Message greeting